version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # 设置为 0，表示不打开 PR
    groups:
      non-breaking-changes:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      non-breaking-changes:
        update-types: [minor, patch]
